// A curated list of short, memorable, easy-to-type words for passphrase generation.
// Deliberately excludes ambiguous/odd words. ~256 entries (~8 bits of entropy per word).
export const WORDLIST: string[] = [
  'apple', 'arrow', 'Atlas', 'aurora', 'avatar', 'badge', 'bamboo', 'beacon',
  'berry', 'blaze', 'blink', 'blossom', 'bluebird', 'breeze', 'brick', 'breeze',
  'butter', 'cabin', 'cactus', 'cadet', 'camera', 'canvas', 'canyon', 'carbon',
  'cascade', 'castle', 'cedar', 'chalk', 'chamber', 'charm', 'cheese', 'cherry',
  'cipher', 'clamor', 'cliff', 'clover', 'cobra', 'comet', 'compass', 'copper',
  'coral', 'cosmos', 'cotton', 'cradle', 'crater', 'creek', 'crisp', 'crystal',
  'curl', 'cypress', 'daisy', 'dancer', 'daring', 'delta', 'denim', 'desert',
  'dewdrop', 'dolphin', 'donut', 'dune', 'dynamo', 'eagle', 'echo', 'ember',
  'emerald', 'engine', 'fable', 'falcon', 'feather', 'ferns', 'fjord', 'flame',
  'flannel', 'fleet', 'flutter', 'forest', 'fossil', 'fountain', 'fox', 'fragrant',
  'frost', 'gadget', 'galaxy', 'gazebo', 'gemini', 'glacier', 'glade', 'glider',
  'goblin', 'golden', 'granite', 'grape', 'gravel', 'griffin', 'grove', 'guppy',
  'gust', 'harbor', 'harvest', 'hatch', 'haven', 'hazel', 'helix', 'heron',
  'hickory', 'hollow', 'honey', 'horizon', 'hunter', 'hydra', 'iceberg', 'indigo',
  'ivy', 'jacket', 'jaguar', 'jasmine', 'jester', 'jingle', 'jovial', 'joyful',
  'kayak', 'kelp', 'kettle', 'keystone', 'kitten', 'knack', 'lagoon', 'lantern',
  'lava', 'lavender', 'leaflet', 'lemon', 'lighthouse', 'lilac', 'lime', 'linden',
  'lobster', 'lodge', 'loon', 'lumen', 'lunar', 'luster', 'magnet', 'mango',
  'maple', 'marble', 'marsh', 'meadow', 'melody', 'meteor', 'mica', 'minuet',
  'mirage', 'mistle', 'monarch', 'moonbeam', 'moss', 'mountain', 'mushroom', 'myrtle',
  'nectar', 'needle', 'nemesis', 'neon', 'nestle', 'nimbus', 'noble', 'nomad',
  'noodle', 'northern', 'nougat', 'oakwood', 'ocean', 'octave', 'olive', 'onion',
  'opal', 'orbit', 'orchid', 'oriole', 'otter', 'oval', 'owl', 'paddle',
  'panda', 'pansy', 'papaya', 'parade', 'paragon', 'parrot', 'passage', 'patch',
  'paulownia', 'pebble', 'pelican', 'penguin', 'pepper', 'perfume', 'petal', 'phlox',
  'piano', 'pickerel', 'pillar', 'pine', 'pioneer', 'pistil', 'pixel', 'plaza',
  'plumage', 'polar', 'pompom', 'ponder', 'poppy', 'porpoise', 'prairie', 'prism',
  'puffin', 'pumpkin', 'puppy', 'quartz', 'quasar', 'quench', 'query', 'quiver',
  'rabbit', 'raccoon', 'radish', 'raptor', 'raspberry', 'ravel', 'redwood', 'reef',
  'reindeer', 'relic', 'rhythm', 'ribbon', 'ridge', 'river', 'robin', 'rocket',
  'rookery', 'rose', 'ruby', 'saffron', 'sage', 'sail', 'sand', 'sapphire',
  'scarlet', 'scout', 'seabird', 'seal', 'season', 'sedge', 'sequoia', 'serene',
  'shadow', 'shamrock', 'shelter', 'shore', 'sienna', 'silken', 'silver', 'skater',
  'skyline', 'slate', 'smoke', 'snapshot', 'snowfall', 'soda', 'solstice', 'sonnet',
  'spark', 'spear', 'spire', 'splash', 'sponge', 'spruce', 'squirrel', 'starling',
  'steel', 'stitch', 'stone', 'stratus', 'stream', 'sugar', 'summit', 'sunset',
  'surf', 'sycamore', 'tadpole', 'talon', 'tamarack', 'tangent', 'tapestry', 'tarn',
  'tarragon', 'tempo', 'tern', 'thatch', 'thistle', 'thrush', 'thunder', 'ticker',
  'tide', 'tinsel', 'topaz', 'torch', 'torrent', 'totem', 'tower', 'tranquil',
  'treetop', 'trillium', 'trot', 'trout', 'tulip', 'tundra', 'turtle', 'twig',
  'twilight', 'umbrella', 'updraft', 'upland', 'valley', 'velvet', 'vermillion', 'vetch',
  'violet', 'violin', 'vortex', 'waffle', 'walnut', 'warbler', 'watch', 'wave',
  'waxwing', 'weaver', 'whale', 'whisker', 'willow', 'wind', 'winter', 'wisteria',
  'wolf', 'wombat', 'woodland', 'yarrow', 'yogurt', 'zenith', 'zephyr', 'zinnia',
];
